#!/bin/bash -x

set -o errexit

VERSION=${VERSION:-$(date +"%Y%m%d")}
ITERATION=${ITERATION:-1}

FN=varnish-batteries_${VERSION}-${ITERATION}_amd64.deb

test -d _build && rm -r _build
mkdir -p _build/usr/lib/varnish/vmods/
cp build/libvmod*.so _build/usr/lib/varnish/vmods/
#

#apt show varnish| grep Provides
BUILD_ABI_VER="varnishabi-8.0"
# FIXME: Doesn't seem to be a way for fpm to add depends on
# manually added Provides like varnishabi-8.0?


rm ${FN} || :
fpm -s dir -t deb \
	--name varnish-batteries \
	-m opensource@isokron.no \
	--architecture amd64 \
	--url "https://github.com/isokron/varnish-batteries/" \
	--license "GPL" \
	--depends "varnish > 6.0" \
	--depends "libcurl4" \
	--depends "libmhash2" \
	--vendor "Isokron AS" \
	--version ${VERSION} \
	--iteration ${ITERATION} \
	--description "The batteries you need for Varnish Cache" \
	-C _build
dpkg -I ${FN}
dpkg -c ${FN}
