#!/bin/bash
GITROOT=../../foreign/gquintard-str

if [ ! -f "vmod_str.vcc" ]; then
        test -f $GITROOT/src/vmod.vcc && ln -s $GITROOT/src/vmod.vcc vmod_str.vcc
        test -f $GITROOT/src/vmod_str.vcc && ln -s $GITROOT/src/vmod_str.vcc
fi


test -f $GITROOT/src/vmod_str.h && ln -s $GITROOT/src/vmod_str.h

echo -e "\n/* Automatically modified by import-source, manual changes may be lost. */\n\n" > vmod_str.c
sed \
	-e 's|#include "vmod_config.h"|#include "cache/cache.h"|g' \
	-e 's|#include "vcc_if.h"|#include "vmod_str_if.h"|g' \
	-e 's|#include "vcc_str_if.h"|#include "vmod_str_if.h"|g' \
	$GITROOT/src/vmod_str.c >> vmod_str.c


for vtcfile in `find $GITROOT/src/tests/ -name \*.vtc`; do
	fn_new=$(basename $vtcfile)
	mkdir -p tests
	echo -e "\n/* Automatically modified by import-source, manual changes may be lost. */\n\n" > "tests/$fn_new"
	sed \
		-e 's|import str;|import str from "${topbuild}/lib/libvmod_str/.libs/";|' \
		$vtcfile >> "tests/$(basename $vtcfile)"
done
