#!/bin/bash
GITROOT=../../foreign/xcir-xcounter

if [ ! -f "vmod_xcounter.vcc" ]; then
        test -f $GITROOT/src/vmod.vcc && ln -s $GITROOT/src/vmod.vcc vmod_xcounter.vcc
        test -f $GITROOT/src/vmod_xcounter.vcc && ln -s $GITROOT/src/vmod_xcounter.vcc
fi


test -f $GITROOT/src/vmod_xcounter.h && ln -s $GITROOT/src/vmod_xcounter.h

echo -e "\n/* Automatically modified by import-source, manual changes may be lost. */\n\n" > vmod_xcounter.c
sed \
	-e 's|#include "vmod_config.h"|#include "cache/cache.h"|g' \
	-e 's|#include "vcc_if.h"|#include "vmod_xcounter_if.h"|g' \
	-e 's|#include "vcc_xcounter_if.h"|#include "vmod_xcounter_if.h"|g' \
	$GITROOT/src/vmod_xcounter.c >> vmod_xcounter.c


for vtcfile in `find $GITROOT/src/tests/ -name \*.vtc`; do
	fn_new=$(basename $vtcfile)
	mkdir -p tests
	sed \
		-e 's|import xcounter;|import xcounter from "${topbuild}/lib/libvmod_xcounter/.libs/";|' \
		$vtcfile >> "tests/$(basename $vtcfile)"
done
